[phases.setup]
nixPkgs = ["ffmpeg", "python3", "python3Packages.pip"]

[phases.install]
cmds = ["pip3 install yt-dlp", "npm ci"]

[phases.build]
cmds = []

[start]
cmd = "export PATH=$PATH:/root/.local/bin && npm start"
